# Generated by Django 3.0.7 on 2023-03-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='model',
            new_name='brand',
        ),
    ]
