# Generated by Django 3.0.7 on 2023-02-25 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auccontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sellDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
