# Generated by Django 3.0.7 on 2023-03-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20230304_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='sold',
        ),
    ]
