# Generated by Django 3.0.7 on 2023-02-25 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_selldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='sellDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
