# Generated by Django 3.0.7 on 2023-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230225_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='sellDate',
            new_name='sell_date',
        ),
    ]
