# Generated by Django 3.0.7 on 2023-02-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20230225_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
