# Generated by Django 3.0.7 on 2023-03-17 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('body_style', models.CharField(blank=True, max_length=100)),
                ('fuel', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('milage', models.IntegerField(blank=True)),
                ('min_price', models.IntegerField(blank=True)),
                ('max_price', models.IntegerField(blank=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
