# Generated by Django 3.0.7 on 2023-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='body_style',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
